### ISSUE TITLE
Failure if allowedOrigins is empty

### ISSUE THREAD

**Issue by PleaseStopAsking** [johnsarie27/ArcGISEnterprise#6]
This call fails with error `Method invocation failed because [System.Object[]] does not contain a method named 'Split'.` when the property is empty such as on a fresh installation.

Further logic is needed to evaluate if the array from allowedOrigins is empty or not before trying to split it.

https://github.com/johnsarie27/ArcGISEnterprise/blob/c07e1bab72e2b0a90aeb8cae7bbad94ff17fd4ac/Public/Get-PortalAllowedOrigins.ps1#L54

![Screenshot 2023-03-23 at 12 51 27 PM](https://user-images.githubusercontent.com/35308946/227276906-45525f0b-1a19-40e7-893e-603bc7cefb87.png)

**Comment by PleaseStopAsking** [comment]
@johnsarie27 I would expect a `null` value to be returned in the event that the array is empty instead of a failure. If I get back a failure, I assume something is wrong with either the site or the code but if a `null` value is returned, I assume everything worked and the value from the property is actually `null`.

**Comment by johnsarie27** [comment]
@PleaseStopAsking - That sounds fair to me.  I'll open a new branch and let you know when it's ready to poke at.

**Comment by johnsarie27** [comment]
@PleaseStopAsking - Give the code in the new branch a try and let me know if it behaves as expected.

**Comment by johnsarie27** [comment]
@PleaseStopAsking - This appears to now work as requested.  I'll create the PR and merge.
